# Generated by Django 2.2 on 2021-05-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeediteam'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileFeedIteam',
            new_name='ProfileFeedItem',
        ),
    ]
